import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const lgSmartRegular = localFont({
  src: './fonts/LGSmartRegular.ttf',
  weight: '400',
  style: 'normal',
  display: 'swap',
  variable: '--font-lg-smart',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={lgSmartRegular.variable}>
      <body className={`${lgSmartRegular.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
